project:
  type: website
  output-dir: docs

website:
  title: "Levant WEPs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - summary_table.qmd
      - references.qmd
  site-url: 'https://pgomba.github.io'
  site-path: '/'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

