project:
  type: website
  output-dir: docs

website:
  title: "Levant WEPs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - summary_table.qmd
      - references.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/pagomba
      - icon: github
        href: https://github.com/pgomba/Levantine_WEPs
  site-url: 'https://pgomba.github.io/Levantine_WEPs'
  site-path: '/'
  open-graph: true
  twitter-card:
    creator: "@pagomba"
    image: images/card.png
    card-style: summary_large_image
    

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

