---
title: "References"
---

Baydoun S, Hani N, Nasser H, Ulian T, Arnold-Apostolides N. Wild leafy vegetables: A potential source for traditional Mediterranean food from Lebanon. Front Sustain Food Syst. 2023;6:597.

Cowan JW, Sakr AH, Shadarevian SB, Sabry ZI. Composition of edible wild plants of Lebanon. J Sci Food Agric. 1963;14(7):484--8.

Marouf M, Batal M, Moledor S, Talhouk SN. Exploring the practice of traditional wild plant collection in Lebanon. Food Cult Soc. 2015;18(3):355--78.

Hani N, Baydoun S, Nasser H, Ulian T, Arnold-Apostolides N. Ethnobotanical survey of medicinal wild plants in the Shouf Biosphere Reserve, Lebanon.

Danin A, Fragman-Sapir O. Flora of Israel - Plant stories: Edible Plants. In 2018 \[cited 2022 Sep 6\]. Available from: https://flora.org.il/en/books/plant-stories-2/

Tukan SK, Takruri HR, Ahmad MN. Food habits and traditional food consumption in the Northern Badia of Jordan. Journal of the Saudi Society for Food and Nutrition. 2011;6.

Takruri HR, Tukan SK, Ahmad MN. Medicinal and edible wild plants used by the community of Northern Badia of Jordan. Jordan Journal of Agricultural Sciences. 2010;4(4).

Hudaib M, Mohammad M, Bustanji Y, Tayyem R, Yousef M, Abuirjeie M, et al. Ethnopharmacological survey of medicinal plants in Jordan, Mujib Nature Reserve and surrounding area. J Ethnopharmacol. 2008;120(1):63--71.

Auda MA. An ethnobotanical uses of plants in the middle area, Gaza Strip, Palestine. Adv Environ Biol. 2011;5(11):3681--7.

Tukan SK, Takruri HR, Al-Eisawi DM. The use of wild edible plants in the Jordanian diet. Int J Food Sci Nutr. 1998;49(3):225--35.

Nawash OS, Al-Assaf A, El-Oqlah A, Omari M. Floristic features, Distribution, and ethnobotany of plants gathered and used by local people from the Mediterranean forest in northern Jordan. Ethnobotany Research and Applications. 2014;12:385--96.

Tohmé G, Tohmé H. Illustrated flora of Lebanon. 2007;620.

Aburjai T, Hudaib M, Tayyem R, Yousef M, Qishawi M. Ethnopharmacological survey of medicinal herbs in Jordan, the Ajloun Heights region. J Ethnopharmacol. 2007;110(2):294--304.

Takruri HR, Humeid MA. Nitrate levels in edible wild herbs and vegetables common in Jordan. Nutr Health. 1988;6(2):89--98.

Ali-Shtayeh MS, Jamous RM, Al-Shafie\' JH, Elgharabah WA, Kherfan FA, Qarariah KH, et al. Traditional knowledge of wild edible plants used in Palestine (Northern West Bank): A comparative study. J Ethnobiol Ethnomed. 2008;4(7):13--1347.

Arnold N, Baydoun S, Chalak L, Raus T. A contribution to the flora and ethnobotanical knowledge of Mount Hermon, Lebanon. Flora Mediterranea. 2015;25:13--55.

Saifan S, Abu Laila K, Tehabsem Z, Hiari M. A window on wild plants in Jordan. Jordan: National Center for Agricultural research & Technology Transfer; 2003.

Oran SA, Al-Eisawi DM. Ethnobotanical survey of the medicinal plants in the central mountains (North-South) in Jordan. Journal of Biodiversity and Environmental Sciences J Bio & Env Sci. 2015;6(3):2220--6663.

Ali-Shtayeh MS, Yaniv Z, Mahajna J. Ethnobotanical survey in the Palestinian area: A classification of the healing potential of medicinal plants. J Ethnopharmacol. 2000;73(1--2):221--32.

Landau S, Muklada H, Markovics A, Azaizeh H. Traditional Uses of *Pistacia lentiscus* in veterinary and human Medicine. 2014;163--80.

Dafni A, Yaniv Z, Palevitch D. Ethnobotanical survey of medicinal plants in northern Israel. J Ethnopharmacol. 1984;10(3):295--310.

Lev E. Ethno-diversity within current ethno-pharmacology as part of Israeli traditional medicine - A review. J Ethnobiol Ethnomed. 2006;2.

Mayer-Chissick U, Lev E. Wild Edible Plants in Israel. Tradition versus cultivation. 2014;9--26.

SA B, D K, K R, Ela M A, L C, Apostolides N A. Ethnobotanical and economic importance of wild plant species of Jabal Moussa Bioreserve, Lebanon. J Ecosyst Ecography. 2017;07(03).

Al-Quran S. Ethnobotany of analgesic/stimulant plants used by the inhabitants of Ajloun, Northern Jordan. Arnaldoa. 2015;22(1):49--58.

Al-Aboudi A, Afifi FU. Plants used for the treatment of diabetes in Jordan: A review of scientific evidence. Pharm Biol. 2011;49(3):221--39.

Houri A, Machaka Houri N. Photographic guide to wild flowers of Lebanon. Chemaly & Chemaly; 2001.

Batal M, Hunter E. Traditional Lebanese recipes based on wild plants: An answer to diet simplification? Food Nutr Bull. 2007;28(2 SUPPL.).

Al-Qura\'n S. Ethnopharmacological survey of wild medicinal plants in Showbak, Jordan. J Ethnopharmacol. 2009;123(1):45--50.

Hanna EM, Friborg KG, Qumsiyeh MB. Temporal change in traditional knowledge and use of wild plants in Artas, Palestine. Palest Explor Q. 2022;154(2):81--94.

Jaradat NA, Abualhasan M. Comparison of phytoconstituents, total phenol contents and free radical scavenging capacities between four Arum species from Jerusalem and Bethlehem. Pharmaceutical Sciences. 2016;22(2):120--5.

Sawsan ASO. Selected wild plant species with exotic flowers from Jordan. Int J Biodivers Conserv. 2015;7(5):308--20.

Zurayk RA, Baalbaki R. Inula crithmoides: A candidate plant for saline agriculture. Arid Soil Research and Rehabilitation. 1996;10(3):213--23.

Zeeni N, Daher CF, Saab L, Mroueh M. *Tragopogon porrifolius* improves serum lipid profile and increases short-term satiety in rats. Appetite. 2014;72:1--7.

Jaradat NA, Damiri B, Abualhasan MN. Antioxidant evaluation for *Urtica urens*, *Rumex cyprius* and *Borago officinalis* edible wild plants in Palestine. Pak J Pharm Sci. 2016;29(1):325--30.

Hassane M, Mariam S, Jean H, Ramez C. Determination of antioxidant activity of saffron taken from the flower of *Crocus sativus* grown in Lebanon. Afr J Biotechnol. 2011;10(41):8093--100.

Khoury M, Stien D, Eparvier V, Ouaini N, El Beyrouthy M. Report on the Medicinal Use of Eleven Lamiaceae Species in Lebanon and Rationalization of Their Antimicrobial Potential by Examination of the Chemical Composition and Antimicrobial Activity of Their Essential Oils. Evidence-based Complementary and Alternative Medicine. 2016;2016.

Zilkah S, Goldschdmidt EE. Myrtle (*Myrtus communis* L.) -- A Native Mediterranean and Cultured Crop Species. 2014;253--67.

Schiller G. Therapeutic Use of Aleppo Pine (*Pinus halepensis* Mill.). 2014;215--24.
