---
title: "Summary Table"
---

```{r echo=FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(gt)

Levant_WEPS_table <- read_excel("Levant_WEPS_table.xlsx", 
                                sheet = "Sheet2")

remove_nums<- function(input_string) {
  result_string <- gsub("[0-9()–,]", "", input_string)
  return(result_string)
}



object<-Levant_WEPS_table%>%
  drop_na(`Family / Scientific name`)%>%
  
  mutate(url=paste0("https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:",Kew_id),
         Crop=ifelse(grepl("†",`Family / Scientific name`),"*",""),
         authors=word(start = 3,end = -1, `Family / Scientific name`),
         authors=gsub("†","",authors),
         `Family / Scientific name`= ifelse(is.na(Kew_id),`Family / Scientific name`, paste0("<a href=",url,">",
                                            "<div style='line-height:125%'><span style='font-style:italic;font-size:16px'>",
                                            word(`Family / Scientific name`, 1,2,sep=" ") ,
                                            "</div> </a>
        <div style='line-height:110%'><span style ='font-weight:bold;color:black;font-size:12px'>",
        authors,
        "</span></div>
        <div style='line-height:100%'><span style ='font-weight:bold;color:grey;font-size:12px'> IPNI: ",
        Kew_id,
        "</span></div>")),

         `Family / Scientific name`= map(`Family / Scientific name`, gt::html))%>%
  filter(`Family / Scientific name`!="NA")%>%
  rename(IPNI=Kew_id)%>%
  select(-url,-IPNI,-authors)%>%
  filter(`Family / Scientific name`!="NA")%>%
  mutate_at(c("Edible use by country", "Edible part(s) used","Medicinal use","EcBot categories","Native in the Levant?"), ~replace_na(.,""))%>%
  mutate_at(c("Edible use by country", "Edible part(s) used","Medicinal use"),remove_nums)%>% 
  mutate(`Edible use by country`=gsub("Is", "1",`Edible use by country` ),
         `Edible use by country`=gsub("Le", "2",`Edible use by country` ),
         `Edible use by country`=gsub("Jo", "3",`Edible use by country` ),
         `Edible use by country`=gsub("Pa", "4",`Edible use by country` ),
         `Edible use by country`=gsub("33", "3,3",`Edible use by country` ),
         `Edible use by country`=gsub("St", "3",`Edible use by country` ),
         `Edible use by country`=str_squish(`Edible use by country`),
         `Edible use by country`=gsub(" ", ",",`Edible use by country`))%>%
  mutate(`Medicinal use`=gsub("Is", "1",`Medicinal use` ),
         `Medicinal use`=gsub("Le", "2",`Medicinal use` ),
         `Medicinal use`=gsub("Jo", "3",`Medicinal use` ),
         `Medicinal use`=gsub("Pa", "4",`Medicinal use` ),
         `Medicinal use`=str_squish(`Medicinal use`),
         `Medicinal use`=gsub(" ", ",",`Medicinal use`),
         `Medicinal use`=ifelse(`Medicinal use`=="","no",`Medicinal use`))%>%
  mutate(`Edible use by country`=ifelse(`Edible use by country`=="","no",`Edible use by country`),
         `Native in the Levant?`=ifelse(`Native in the Levant?`=="Yes","Yes",""))%>%
  
  gt()%>%
  tab_header(
    title = md("A scientific review of Wild Edible Plants from the Levant - Summary Table"),
    subtitle = md("Fr - Fruit, In - Inflorescences, Lf - Leaf, Rt - Root, Sd - Seed, St - Stems, Wp - Whole plant || F - Food, FA - Food additive, M - Medicinal <br><br> Suggested citation: Gómez Barreiro, P., Coleshill, D., Abulaila, K.,; Howes, Howes, M.J.R., Hani, N., Ulian, T. (2023). A scientific review of Wild Edible Plants from the Levant. figshare. Dataset. https://doi.org/10.6084/m9.figshare.24101223.v1")
  )%>%
  cols_align(
    align = "center",
    columns = everything()
  )%>%
  cols_align(
    align = "left",
    columns = `Family / Scientific name`
  )%>%
  
  opt_align_table_header(align = "left")%>%
  fmt_image(
    columns = `Edible use by country`,
    path = "images/",
    file_pattern = "{x}.png")%>%
  fmt_image(
    columns = `Medicinal use`,
    path = "images/",
    file_pattern = "{x}.png")%>%
  tab_footnote(
    footnote = "Identified as crops via Food and Agriculture Organization's crop list (FAO, 2015)",
    locations = cells_column_labels(
      columns = Crop))
```

```{r echo=FALSE}
object |> as_raw_html()
```
